name: Publish LazyHttpServerLib to NuGet

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore LazyHttpServerLib/LazyHttpServerLib.csproj

      - name: Build
        run: dotnet build --no-restore --configuration Release --version-suffix "ci${{ github.run_number }}" LazyHttpServerLib/LazyHttpServerLib.csproj

      - name: Pack
        run: dotnet pack --no-build --no-restore --configuration Release --version-suffix "ci${{ github.run_number }}" -o artifact/ LazyHttpServerLib/LazyHttpServerLib.csproj

      - name: Publish
        run: dotnet nuget push "artifact/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
