name: Publish LazyHttpServerLib to GitHub Packages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Ensure GitHub NuGet Source
      run: |
        dotnet nuget add source \
          --name github \
          --username mkaraki \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          "https://nuget.pkg.github.com/mkaraki/index.json"
        
    - name: Restore dependencies
      run: dotnet restore LazyHttpServerLib/LazyHttpServerLib.csproj
      
    - name: Build
      run: dotnet build --no-restore --configuration Release LazyHttpServerLib/LazyHttpServerLib.csproj

    - name: Pack
      run: dotnet pack --no-build --no-restore --configuration Release --version-suffix "build${{ github.run_number }}" -o artifact/ LazyHttpServerLib/LazyHttpServerLib.csproj
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: LazyHttpServerLib
        path: artifact/
    
    - name: Publish
      run: dotnet nuget push "artifact/*.nupkg" --source "github"
